### ISSUE TITLE
Does it work for react-native android perfectly ? 

### ISSUE THREAD

**Issue by KiranreddySrDev** [Starotitorov/react-native-deep-link#1]
I have been searching for react-native deep linking in react-native project. Finally I got it this project, Can I get this package correctly. I mean does it work for IOS and Android ?
Please let me know thanks

**Comment by Starotitorov** [comment]
@getinfyKiranreddy, thank you for the question! Yes, this package works perfectly on both iOS and Android. This repo contains two example applications, you can find them in `example/` and `NavigationServiceExample/` directories of the repo. This applications are configured only for Android now, but in general, you can configure them for iOS too, in the README.md I provided [instructions](https://github.com/Starotitorov/react-native-deep-link#configuring-ios). If you would like to run the applications on your device or emulator, the only things you need to do are install dependencies in the root folder of the application using `npm install` and then run `react-native run-android`. Also, I wrote [an article](https://medium.com/the-react-native-log/handle-deep-links-in-react-native-apps-b22055149b3a) with a step by step implementation of the application inside `example/` directory. The API of the package has changed a little bit, but the configuration steps are the same and described in the article too.

**Comment by Starotitorov** [comment]
I am going to close this, feel free to reopen the issue if you have more questions.

**Comment by KiranreddySrDev** [comment]
Thanks, I'll check it out

But I need to check it once if It does not work in an android then I will
let you know.Can you help me out ?
