### ISSUE TITLE
Without redux

### ISSUE THREAD

**Issue by vre142** [Starotitorov/react-native-deep-link#7]
Hi can I use this library without use redux?
Thanks

**Comment by Starotitorov** [comment]
Hi @vre142, the package does not require Redux as a dependency, so you can use it in React Native applications without Redux. I mentioned this in the README.md.

**Comment by Starotitorov** [comment]
The repository contains an example of such application, you can find it [here](https://github.com/Starotitorov/react-native-deep-link/tree/master/NavigationServiceExample).
