### ISSUE TITLE
How do you deal with dynamic queries?

### ISSUE THREAD

**Issue by haveamission** [Starotitorov/react-native-deep-link#8]
I have this setup:

export default createDeepLinkingHandler([{
    name: 'exampledomain',
    routes: [{
        expression: '/chat/:merchant',
        callback: handleMerchantMessage
    },
    {
        expression: '/callbackuri',
        callback: handleCallBack
    }
    ]
}]);

However I am getting values like so:
`exampledomain://callbackUri?state=faddf1f1-a667-4248-bfc0-0b0d42c3a315&session_state=b15b2e24-28fb-4b4c-959f-6ae3525f209d&code=b1e1e052-c46b-416f-ab75-6aafc2403883.b15b2e24-28fb-4b4c-959f-6ae3525f209d.c563ae1c-939a-4c97-82f2-6e92a5b6f8c3 was not found.`

How am I supposed to deal with this?

**Comment by Starotitorov** [comment]
Hi, you added a route expression `/callbackuri` to the schemes config, but there is a capital `U` in the URL you provided, check the spelling of the path in the URL `/callbackUri`. Also, you should add `:` to the scheme name in the scheme definition.
```
export default createDeepLinkingHandler([{
  name: 'exampledomain:',
  routes: []
}]);
```

**Comment by Starotitorov** [comment]
Feel free to reopen the issue in case you have more questions.
