### ISSUE TITLE
Error: The route /chat/:merchant callback is not a higher order function.

### ISSUE THREAD

**Issue by haveamission** [Starotitorov/react-native-deep-link#9]
I have the following scheme:

```
const schemes = [
    {
        name: 'company:',
        routes: [
            {
                expression: '/chat/:merchant',
                callback: handleMerchantMessage
            },
            {
                expression: '/detail/:merchant',
                callback: handleMerchantNotice
            },
            {
                expression: '/callbackuri',
                callback: handleCallBack,
                query: {
                    "state": "state",
                    "session_state": "session_state",
                    "code": "code",
                }
            }
        ]
    },
    {
        name: 'https:',
        routes: [
            {
                expression: 'https://company.onelink.me/QOVp/d8e6a2e0?af_dp=:merchant',
                callback: handleDeferredDeeplink
            }
        ]
    }
]

export default createDeepLinkingHandler(schemes);
```

And the following functions:

```
export const handleMerchantMessage = () => {
    pushNotificationBase();
}

export const handleMerchantNotice = () => {
    pushNotificationBase();
}

export const handleDeferredDeeplink = () => {
}

export const handleCallBack = () => {
    pushNotificationBase();
}
```

I get:

`Error: The route /chat/:merchant callback is not a higher order function.`

These look very similar to your example in handlers... why am I receiving the above error message? How do I change my code to fix it?

**Comment by Starotitorov** [comment]
A higher order function is a function that takes a function as an argument, or returns a function.
In our case all functions like handleMerchantMessage, handleMerchantNotice, handleDeferredDeeplink, handleCallBack should return functions.

```
export const handleMerchantMessage = () => () => {
    pushNotificationBase();
}

export const handleMerchantNotice = () => () => {
    pushNotificationBase();
}

export const handleDeferredDeeplink = () => () => {
}

export const handleCallBack = () => () => {
    pushNotificationBase();
}
```

Recompose, redux-thunk packages have similar API. The idea behind this is to merge data from several sources, in this case some parameters are stored in closure.

handleMerchantMessage function receives the result of url parsing, the function returns another function which receives component props as an argument.

```
export const handleMerchantMessage = ({ scheme, route, query, params }) => ({ dispatch }) => {
}
```

Also, where did you find this code in the docs? The package does not provide such API. :sweat_smile:

```
query: {
    "state": "state",
    "session_state": "session_state",
    "code": "code",
}
```

**Comment by haveamission** [comment]
Oops, my fault on the query part - I misinterpreted something written in the docs.

And thank you, that worked.

**Comment by haveamission** [comment]
Also, how would I wrap the function in a router correctly?

Like so?

const handleMerchantMessagePre = () => () => {
    pushNotificationBase();
}

const handleMerchantMessage = withRouter(handleMerchantMessagePre);

**Comment by Starotitorov** [comment]
withRouter is a [HOC](https://reactjs.org/docs/higher-order-components.html), only React components can be wrapped with HOCs.

So, you should do something like this:

```
export default compose(
  withRouter,
  createDeepLinkingHandler(schemes)
)(YourComponent)
```

withRouter will pass some props to the WrappedComponent. This props will be available in your callback handler:

```
const handleMerchantMessage = () => ({ location, history, dispatch }) => {
  // Now you have access to the history and location here in the code
}
```

**Comment by haveamission** [comment]
Beautiful, thank you!

**Comment by haveamission** [comment]
I actually switched it to just using the history rather than the HOC.

Final question I think (thanks for being so helpful).

I am trying to use this link:

    {
        name: 'https:',
        routes: [
            {
                expression: 'company.onelink.me/QOVp/d8e6a2e0?af_dp=:merchant',
                callback: handleDeferredDeeplink
            }
        ]
    }

https://company.onelink.me/QOVp/d8e6a2e0?af_dp=:merchant

However when I try to use this, I get an error that a handler for the route was not found.

How am I not handling this route correctly?

**Comment by Starotitorov** [comment]
@haveamission, query parameters are not a part of pathname, you should omit them in the route expression.

```
    name: 'https:',
    routes: [
        {
            expression: 'company.onelink.me/QOVp/d8e6a2e0',
             callback: handleDeferredDeeplink
        }
    ]
}
```

**Comment by Starotitorov** [comment]
Query parameters are not a part of pathname, you should omit them in route expression. are not a part of pathname, you should omit them in the route expression.

```
{    
    name: 'https:',
    routes: [
        {
            expression: 'company.onelink.me/QOVp/d8e6a2e0',
             callback: handleDeferredDeeplink
        }
    ]
}
```

**Comment by Starotitorov** [comment]
I am going to close the issue. Feel free to reopen it in case you have more questions.
